-- 2022/3의 오프라인/온라인 상품 판매 데이터의 판매 날짜, 상품id, 유저id, 판매량
-- off의 user_id = null, 판매일 기준 오름차순, 상품 id 오름차순, 유저 id 오름차순
WITH TBL AS (
    SELECT
    SALES_DATE,
    PRODUCT_ID,
    NULL AS USER_ID,
    SALES_AMOUNT
    FROM OFFLINE_SALE
    WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-03'
    UNION ALL
    SELECT
    SALES_DATE,
    PRODUCT_ID,
    USER_ID,
    SALES_AMOUNT
    FROM ONLINE_SALE
    WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-03'
)
SELECT
DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE,
PRODUCT_ID,
USER_ID,
SALES_AMOUNT
FROM TBL
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC