-- USER_INFO 테이블과 ONLINE_SALE 테이블에서 년, 월, 성별 별로 상품을 구매한 회원수를 집계
WITH TBL AS (
    SELECT
    O.USER_ID,
    SALES_DATE,
    GENDER
    FROM USER_INFO AS I
    JOIN ONLINE_SALE AS O
    ON I.USER_ID = O.USER_ID
    WHERE I.GENDER IS NOT NULL
)
SELECT
YEAR(SALES_DATE) AS YEAR,
MONTH(SALES_DATE) AS MONTH,
GENDER,
COUNT(DISTINCT USER_ID) AS USERS
FROM TBL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER