-- 크기가 100이하면 low, 100초과 1000이하면 medium, 1000초과면 high
-- id에 대해 오름차순, id,size출력
SELECT
E.ID,
CASE
    WHEN E.SIZE_OF_COLONY > 1000 THEN 'HIGH'
    WHEN E.SIZE_OF_COLONY <= 100 THEN 'LOW'
    ELSE 'MEDIUM'
END AS SIZE
FROM ECOLI_DATA E
ORDER BY E.ID