-- 코드를 입력하세요
WITH TBL AS (
    SELECT
    FLAVOR,
    SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
)
SELECT
F.FLAVOR
FROM FIRST_HALF F
JOIN TBL
ON F.FLAVOR = TBL.FLAVOR
ORDER BY F.TOTAL_ORDER + TBL.TOTAL_ORDER DESC
LIMIT 3