-- 0-23시까지 각 시간대별로 입양이 몇 건 발생했는지 조회(시간대 순 정렬)
WITH TBL AS (
    SELECT
    0 AS H
    UNION ALL SELECT 1
    UNION ALL SELECT 2
    UNION ALL SELECT 3
    UNION ALL SELECT 4
    UNION ALL SELECT 5
    UNION ALL SELECT 6
    UNION ALL SELECT 7
    UNION ALL SELECT 8
    UNION ALL SELECT 9
    UNION ALL SELECT 10
    UNION ALL SELECT 11
    UNION ALL SELECT 12
    UNION ALL SELECT 13
    UNION ALL SELECT 14
    UNION ALL SELECT 15
    UNION ALL SELECT 16
    UNION ALL SELECT 17
    UNION ALL SELECT 18
    UNION ALL SELECT 19
    UNION ALL SELECT 20
    UNION ALL SELECT 21
    UNION ALL SELECT 22
    UNION ALL SELECT 23
)
SELECT
H AS HOUR,
COUNT(ANIMAL_ID)
FROM TBL
LEFT JOIN ANIMAL_OUTS A ON H = HOUR(DATETIME)
GROUP BY H