-- DEVELOPERS 테이블에서 Front End 스킬을 가진 개발자의 정보를 조회하려 합니다.
WITH FE AS (
    SELECT
    SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
    GROUP BY CATEGORY
)
SELECT
ID,
EMAIL,
FIRST_NAME,
LAST_NAME
FROM DEVELOPERS D
JOIN FE
ON FE.CODE & D.SKILL_CODE
ORDER BY ID