-- 코드를 입력하세요
# WITH TBL AS (
#     SELECT 1 AS H
#     UNION ALL SELECT 2
#     UNION ALL SELECT 3
#     UNION ALL SELECT 4
#     UNION ALL SELECT 5
#     UNION ALL SELECT 6
#     UNION ALL SELECT 7
#     UNION ALL SELECT 8
#     UNION ALL SELECT 9
#     UNION ALL SELECT 10
#     UNION ALL SELECT 11
#     UNION ALL SELECT 12
#     UNION ALL SELECT 13
#     UNION ALL SELECT 14
#     UNION ALL SELECT 15
#     UNION ALL SELECT 16
#     UNION ALL SELECT 17
#     UNION ALL SELECT 18
#     UNION ALL SELECT 19
# )
SELECT
HOUR(DATETIME) AS HOUR,
COUNT(*)
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN 9 AND 19
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME)