-- 테이블에서 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회
WITH TBL AS (
    SELECT
    MEMBER_ID,
    COUNT(*) AS CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY CNT DESC
),
MAX_WRITER AS (
    SELECT MEMBER_ID
    FROM TBL
    WHERE CNT = (SELECT MAX(CNT) AS CNT FROM TBL)
)
SELECT
MEMBER_NAME,
REVIEW_TEXT,
DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R
JOIN MAX_WRITER M
ON M.MEMBER_ID = R.MEMBER_ID
JOIN MEMBER_PROFILE F
ON F.MEMBER_ID = M.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT