-- RARITY = 'RARE'인 아이템의 모든 다음 업그레이드 아이템의 아이템 ID, NAME, RARITY
-- ID 기준 내림차순(ROOT를 제외한 모든 트리?)
SELECT 
I.ITEM_ID,
I.ITEM_NAME,
I.RARITY
FROM ITEM_INFO I
JOIN ITEM_TREE T
-- ?
ON I.ITEM_ID = T.ITEM_ID
JOIN ITEM_INFO P
-- 부모가 있는 것만 남기기
ON P.ITEM_ID = T.PARENT_ITEM_ID
WHERE P.RARITY = 'RARE'
ORDER BY I.ITEM_ID DESC