-- RARITY = 'RARE'인 아이템의 모든 다음 업그레이드 아이템의 아이템 ID, NAME, RARITY
-- ID 기준 내림차순(ROOT를 제외한 모든 트리?)
SELECT
C.ITEM_ID,
C.ITEM_NAME,
C.RARITY
FROM ITEM_INFO C
JOIN ITEM_TREE T
ON T.ITEM_ID = C.ITEM_ID
JOIN ITEM_INFO P
ON T.PARENT_ITEM_ID = P.ITEM_ID
WHERE P.RARITY = 'RARE'
ORDER BY C.ITEM_ID DESC