# 부모의 형질을 모두 보유한 대장균의 ID, GENOTYPE, PARENT_GENOTYPE 출력
# 일단 부모가 있는 대장균만 얻기(inner join)
# & 연산으로 부모 형질 모두 보유 판별
SELECT
C.ID,
C.GENOTYPE,
P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA C
JOIN ECOLI_DATA P
ON P.ID = C.PARENT_ID
WHERE (P.GENOTYPE & C.GENOTYPE) = P.GENOTYPE
ORDER BY C.ID