# 부모의 형질을 모두 보유한 대장균의 ID, GENOTYPE, PARENT_GENOTYPE 출력
SELECT
C.ID,
C.GENOTYPE,
P.GENOTYPE AS 'PARENT_GENOTYPE'
FROM ECOLI_DATA AS C
JOIN ECOLI_DATA AS P
ON C.PARENT_ID = P.ID
WHERE (C.GENOTYPE & P.GENOTYPE) = P.GENOTYPE
ORDER BY C.ID
