-- 대여 시작일을 기준으로 2022년 8월부터 2022년 10월까지 총 대여 횟수가 5회 이상인 자동차들에 대해서 해당 기간 동안의 월별 자동차 ID 별 총 대여 횟수(컬럼명: RECORDS) 리스트를 출력
-- 월을 기준으로 오름차순 정렬하고, 월이 같다면 자동차 ID를 기준으로 내림차순 정렬
-- 총 대여 횟수가 0은 제외
WITH TBL AS (
    SELECT
    CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
SELECT
MONTH(START_DATE) AS MONTH,
RH.CAR_ID,
COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
JOIN TBL
ON RH.CAR_ID = TBL.CAR_ID
WHERE RH.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH, RH.CAR_ID
ORDER BY MONTH ASC, RH.CAR_ID DESC