-- Python or C#
WITH TBL AS (
    SELECT
    SUM(CODE) AS SKILL_CODE
    FROM SKILLCODES
    WHERE NAME in ('Python','C#')
)
SELECT
ID,
EMAIL,
FIRST_NAME,
LAST_NAME
FROM DEVELOPERS D, TBL
WHERE D.SKILL_CODE & TBL.SKILL_CODE != 0
ORDER BY ID