-- 코드를 작성해주세요
WITH TBL AS (
    SELECT
    SUM(S.CODE) AS SKILL
    FROM SKILLCODES S
    WHERE NAME IN ('C#','Python')
)
SELECT
D.ID,
D.EMAIL,
D.FIRST_NAME,
D.LAST_NAME
FROM TBL
JOIN DEVELOPERS D
ON D.SKILL_CODE & TBL.SKILL != 0
ORDER BY D.ID ASC