-- 분화된 연도, 분화된 연도별 대장균 크기의 편차, 대장균 개체의 ID
-- 분화된 연도별 대장균 크기의 편차 = 가장 큰 대장균 크기 - each
-- 연도 asc, 대장균 크기 asc
WITH TBL AS (
    SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEARS,
    MAX(SIZE_OF_COLONY) AS MX
    FROM ECOLI_DATA
    GROUP BY YEARS
)
SELECT 
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    TBL.MX - E.SIZE_OF_COLONY AS YEAR_DEV,
    E.ID
FROM ECOLI_DATA E
JOIN TBL
ON TBL.YEARS = YEAR(E.DIFFERENTIATION_DATE)
ORDER BY YEAR,YEAR_DEV