-- 분화된 연도, 분화된 연도별 대장균 크기의 편차, 대장균 개체의 ID
-- 분화된 연도별 대장균 크기의 편차 = 가장 큰 대장균 크기 - each
-- 연도 asc, 대장균 크기 asc
WITH TBL AS (
    SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    MAX(SIZE_OF_COLONY) AS SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT
YEAR(DIFFERENTIATION_DATE) AS YEAR,
(TBL.SIZE - SIZE_OF_COLONY) AS YEAR_DEV,
ID
FROM ECOLI_DATA
JOIN TBL ON TBL.YEAR = YEAR(DIFFERENTIATION_DATE)
ORDER BY YEAR ASC, YEAR_DEV ASC