-- BASS, SNAPPER의 수
WITH TBL AS (
    SELECT
    FISH_NAME
    FROM FISH_INFO I
    JOIN FISH_NAME_INFO N
    ON I.FISH_TYPE = N.FISH_TYPE
)
SELECT
COUNT(*) AS FISH_COUNT
FROM TBL
WHERE FISH_NAME IN ('BASS','SNAPPER')