-- 상반기 총주문량이 3000보다 높으면서 주 성분이 과일인 아이스크림을 총주문량 내림차순
SELECT
H.FLAVOR
FROM FIRST_HALF H
JOIN ICECREAM_INFO I
ON H.FLAVOR = I.FLAVOR
WHERE H.TOTAL_ORDER >= 3000 AND I.INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC