WITH TBL AS (
    SELECT
    I.FISH_TYPE,
    MAX(I.LENGTH) AS MX
    FROM FISH_INFO I
    GROUP BY I.FISH_TYPE
)
SELECT
I.ID,
N.FISH_NAME,
I.LENGTH
FROM FISH_INFO I
JOIN FISH_NAME_INFO N
ON I.FISH_TYPE = N.FISH_TYPE
JOIN TBL
ON TBL.FISH_TYPE = N.FISH_TYPE
AND I.LENGTH = TBL.MX
ORDER BY I.ID