-- 물고기 종류 별 가장 큰 물고기의 id,name,length -> id asc
WITH TBL AS (
    SELECT
    FISH_NAME,
    MAX(LENGTH) AS LENGTH
    FROM FISH_INFO I
    JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
    GROUP BY FISH_NAME
)
SELECT
I.ID,
N.FISH_NAME,
I.LENGTH
FROM FISH_INFO I
JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
JOIN TBL ON TBL.LENGTH = I.LENGTH AND N.FISH_NAME = TBL.FISH_NAME
ORDER BY ID