-- 2022년도 한해 평가 점수가 가장 높은 사원 정보를 조회
WITH TBL AS (
    SELECT
    SUM(SCORE) AS TOTAL,
    EMP_NO
    FROM HR_GRADE H
    GROUP BY EMP_NO
)
SELECT
TOTAL AS SCORE,
E.EMP_NO,
E.EMP_NAME,
E.POSITION,
E.EMAIL
FROM TBL
JOIN HR_EMPLOYEES E
ON E.EMP_NO = TBL.EMP_NO
JOIN HR_DEPARTMENT D
ON D.DEPT_ID = E.DEPT_ID
WHERE TOTAL = (SELECT MAX(TOTAL) FROM TBL)